### ISSUE TITLE
Interfaz gráfica: Ajustar ancho

### ISSUE THREAD

**Issue by hector231091** [hector231091/control_colores_lacado_II#1]
Ajustar el ancho de todas las celdas de la interfaz gráfica para que, independientemente del tamaño de la ventana, todos los pulsadores y las etiquetas que se muestran se ajusten a la pantalla.

**Comment by hector231091** [comment]
En principio ya estaría hecha. Compruébalo con tu PC a ver si se te ajusta todo al tamaño de la pantalla y si es así la finalizo.

**Comment by siempredelao** [comment]
Todo correcto, cierro este issue.
