### ISSUE TITLE
Interfaz gráfica: Entry Colores y Bastidores

### ISSUE THREAD

**Issue by hector231091** [hector231091/control_colores_lacado_II#4]
En el primer inicio del programa, la primera tecla que se pulsa al meter un color o una observación no sale por pantalla.

**Comment by siempredelao** [comment]
No he sido capaz de reproducir este fallo, ¿tú puedes?

**Comment by hector231091** [comment]
En el campo de los colores no, ya no sucede, pero en el de las observaciones sí que me pasa. Lo único que solo pasa la primera vez que se pone una observación, el resto de veces ya salen bien.

**Comment by hector231091** [comment]
Solucionado.
