### ISSUE TITLE
Interfaz gráfica: Habilitación botones horas

### ISSUE THREAD

**Issue by hector231091** [hector231091/control_colores_lacado_II#6]
Habilitar y deshabilitar cada uno de los botones de las horas con un orden lógico:

1.- Hora inicio cambio color=on, resto=off
2.- Hora inicio color=on, resto=off
3.- Hora fin color=on, resto=off

**Comment by siempredelao** [comment]
Cierro este issue porque la funcionalidad que se describe ya está hecha.
